version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python2 -m virtualenv pl
            . pl/bin/activate
            pip install -U platformio
            platformio update

      - run:
          name: platformio run
          command: |
            . pl/bin/activate
            platformio run